name: Release
on:
  push:
    branches: ['main']

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: JasonEtco/build-and-tag-action@v2
        with:
          tag_name: v0.0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
